# Permalinks
permalink:        pretty
# Setup
title:            '@zhukserega'
url:              http://seregazhuk.me
baseurl:          /
author:
  name:           Zhuk Sergey
  url:            http://seregazhuk.me
  email:          seregazhuk88@gmail.com
  description:	  'I am Zhuk Sergey, a full stack web developer.'
# Pagination
paginate: 15
paginate_path: "/blog/page/:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/seregazhuk/seregazhuk.github.io

exclude: [vendor]
