# Permalinks
permalink:        pretty
# Setup
title:            '@zhukserega'
url:              http://seregazhuk.github.io
baseurl:          /
author:
  name:           Zhuk Sergey
  url:            http://seregazhuk.github.io
  email:          seregazhuk88@gmail.com
  description:	  'I am Zhuk Sergey, a full stack web developer.'
# Pagination
pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/seregazhuk/seregazhuk.github.io

exclude: [vendor]
